# Generated by Django 4.1.1 on 2022-09-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="latitude",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="longitude",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
