# Generated by Django 4.1.1 on 2022-09-12 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_is_staff_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="user",
            field=models.OneToOneField(
                default="",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
