# Generated by Django 4.1.1 on 2022-09-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cpf",
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
