# Generated by Django 4.1.1 on 2022-09-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="event",
            name="adress_id",
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(),
        ),
    ]
