# Generated by Django 4.1.1 on 2022-09-08 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="address",
        ),
    ]
