# Generated by Django 4.1 on 2022-09-06 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_event_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="photo",
        ),
    ]
