# Generated by Django 4.1.1 on 2022-09-14 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0001_initial"),
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="full_age",
            new_name="classification",
        ),
        migrations.AlterField(
            model_name="event",
            name="address",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="addresses.address",
            ),
        ),
    ]
