# Generated by Django 4.1 on 2022-09-08 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0001_initial"),
        ("events", "0002_rename_user_id_event_user_remove_event_adress_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="photo",
        ),
        migrations.AddField(
            model_name="event",
            name="address",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="addresses.address",
            ),
            preserve_default=False,
        ),
    ]
