# Generated by Django 4.1.1 on 2022-09-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="revenue",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="total_sold_tickets",
            field=models.IntegerField(default=0),
        ),
    ]
