# Generated by Django 4.1.1 on 2022-09-12 16:22

import cloudinary.models
from django.db import migrations
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_event_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="photo",
            field=cloudinary.models.CloudinaryField(
                default=1, max_length=255, validators=[events.models.validate_file_size]
            ),
            preserve_default=False,
        ),
    ]
