# Generated by Django 4.1 on 2022-09-08 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_remove_event_photo_event_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="address",
        ),
        migrations.RemoveField(
            model_name="event",
            name="user",
        ),
    ]
