# Generated by Django 4.1.1 on 2022-09-14 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_revenue_event_total_sold_tickets"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="revenue",
        ),
        migrations.RemoveField(
            model_name="event",
            name="total_sold_tickets",
        ),
    ]
