# Generated by Django 4.1.1 on 2022-09-10 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_alter_event_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="photo",
        ),
    ]
