FROM postgres:14.1


RUN apt-get install curl -y
RUN apt-get update && apt-get  install -y postgresql-14-postgis-3  
RUN apt-get install binutils libproj-dev gdal-bin


CMD ["/usr/local/bin/docker-entrypoint.sh","postgres"]