# Generated by Django 4.1.1 on 2022-09-14 22:30

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("price", models.FloatField()),
                ("revenue", models.FloatField(default=0)),
                ("quantity", models.IntegerField()),
                ("total_sold_tickets", models.IntegerField(default=0)),
                ("due_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("number_batch", models.SmallIntegerField()),
            ],
        ),
    ]
