# Generated by Django 4.1.1 on 2022-09-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("batchs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="batch",
            old_name="id",
            new_name="batch_id",
        ),
    ]
