# Generated by Django 4.1.1 on 2022-09-12 18:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("batchs", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batch",
            name="batch_id",
        ),
        migrations.AddField(
            model_name="batch",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
