# Generated by Django 4.1.1 on 2022-09-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batchs", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="total_sold_tickets",
            field=models.IntegerField(default=0),
        ),
    ]
