# Generated by Django 4.1.1 on 2022-09-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batchs", "0003_remove_batch_batch_id_batch_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="number_batch",
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
