# Generated by Django 4.1.1 on 2022-09-12 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
        ("zones", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zone",
            name="event",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="zones",
                to="events.event",
            ),
            preserve_default=False,
        ),
    ]
