# Generated by Django 4.1.1 on 2022-09-14 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zones", "0002_zone_total_sold_tickets"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zone",
            name="total_sold_tickets",
        ),
    ]
