# Generated by Django 4.1.1 on 2022-09-13 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zones", "0002_rename_total_selled_tickets_zone_total_tickets_sold"),
    ]

    operations = [
        migrations.RenameField(
            model_name="zone",
            old_name="total_tickets_sold",
            new_name="total_sold_tickets",
        ),
    ]
