# Generated by Django 4.1.1 on 2022-09-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zones", "0003_remove_zone_total_sold_tickets"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zone",
            name="total_selled_tickets",
        ),
        migrations.AddField(
            model_name="zone",
            name="total_sold_tickets",
            field=models.IntegerField(default=0),
        ),
    ]
